model: cfa
net: resnet18
data_size: 256
data_crop_size: 256
mask_size: 256
mask_crop_size: 256
gamma_c: 1
gamma_d: 1
lr: 1e-3
weight_decay: 5e-4
num_epochs: 30
train_batch_size: 4
valid_batch_size: 4
train_aug_type: normal
valid_aug_type: normal