model: patchcore2d
# resnet18/wide_resnet50
backbone: wide_resnet50
coreset_sampling_ratio: 0.001
n_neighbours: 9
lr: 0.0001
num_epochs: 1 
batch_size: 32
train_aug_name: normal
valid_aug_name: normal

