import os
import json
import numpy as np
import cv2
from tqdm import tqdm
import sys
sys.path.append('./')

from tools.utils import create_folders

__all__ = ['NAIL', '01']

def process(classes=['01'], clip_size=(1000, 1000)):
    for category in classes:
        # process normal samples
        img_src_folder = '/ssd2/m3lab/data/open-ad/nail/{}/src/normal/'.format(category)
        img_dst_folder = '/ssd2/m3lab/data/open-ad/nail/{}/dst/normal/'.format(category)

        create_folders(img_dst_folder)
        for root, dirs, files in os.walk(img_src_folder):
            print('laod {} normal images done!'.format(len(files)))

        for file in tqdm(files):
            image = cv2.imread(root + file)
            img_resize = cv2.resize(image, clip_size)
            img_path = img_dst_folder + file.replace('.JPG', '.jpg')
            cv2.imwrite(img_path, img_resize) 

        # process anormaly samples
        img_src_folder = '/ssd2/m3lab/data/open-ad/nail/{}/src/anomaly/'.format(category)
        img_dst_folder = '/ssd2/m3lab/data/open-ad/nail/{}/dst/anomaly/'.format(category)
        mask_dst_folder = '/ssd2/m3lab/data/open-ad/nail/{}/dst/anomaly_mask/'.format(category)
        annotation_json_path = '/ssd2/m3lab/data/open-ad/nail/{}/src/via_project_6Dec2022_11h26m.json'.format(category)

        create_folders(img_dst_folder)
        create_folders(mask_dst_folder)

        # load json generated by VIA tool
        annotations = json.load(open(annotation_json_path, 'r'))
        imgs = annotations['_via_img_metadata']
        print('laod {} anormaly images done!'.format(len(imgs)))

        for i, imgId in enumerate(tqdm(imgs)):
            filename = imgs[imgId]['filename']
            regions = imgs[imgId]['regions']
            if len(regions) <= 0:
                continue
    
            # create new mask with all zeros
            image_path = os.path.join(img_src_folder, filename)
            image = cv2.imread(image_path)
            height, width = image.shape[:2]   
            mask_image = np.zeros((height, width), dtype=np.uint8)

            for region in regions:
                # capture attributes
                polygons = region['shape_attributes']

                countOfPoints = len(polygons['all_points_x'])
                points = [None] * countOfPoints
                for i in range(countOfPoints):
                    x = int(polygons['all_points_x'][i])
                    y = int(polygons['all_points_y'][i])
                    points[i] = [x, y]

                contours = np.array([points])
                mask_image = cv2.fillPoly(mask_image, contours, 255)

            # save src img
            img_resize = cv2.resize(image, clip_size)
            img_path = img_dst_folder + filename.replace('.JPG', '.jpg')
            cv2.imwrite(img_path, img_resize)

            # save mask
            img_resize = cv2.resize(mask_image, clip_size)
            img_path = mask_dst_folder + filename.replace('.JPG', '_mask.jpg')
            cv2.imwrite(img_path, img_resize)

if __name__ == '__main__':

    classes = ['01']
    clip_size = (1000, 1000)

    process(classes, clip_size)
