dataset: mvtec3d
seed: 1000
data_path: '/disk/mvtec/3D'
gpu_id: 3
gpu_ids:
- '01234567'
num_workers: 4
batch_size: 8
cl: False
data_size: 224
mask_size: 224
class_names: tire
lr: 0.0001
num_epochs: 300 
depth_duplicate: 1 
milestones_lower: 240
milestones_upper: 270
aug_method: DRAEM
lambda_seg: 1.0
lambda_ssim: 1.0
lambda_l2: 1.0